# Generated by Django 6.0.2 on 2026-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='software/files/'),
        ),
    ]
