# Generated by Django 6.0.2 on 2026-03-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0002_software_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('mdm files', 'Mdm Files'), ('tools', 'Tools')], default='tools'),
        ),
    ]
