# Generated by Django 6.0.2 on 2026-03-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0003_category_software_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='file',
        ),
        migrations.AddField(
            model_name='software',
            name='license_keys',
            field=models.TextField(blank=True, help_text='Enter one license key per line', null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='mdm_download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='mdm_file',
            field=models.FileField(blank=True, null=True, upload_to='software/files/'),
        ),
        migrations.AddField(
            model_name='software',
            name='tool_download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('mdm_files', 'MDM Files'), ('tools', 'Tools')], default='tools', max_length=20),
        ),
    ]
