# Generated by Django 6.0.2 on 2026-03-14 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0004_remove_software_file_software_license_keys_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='license_keys',
        ),
        migrations.RemoveField(
            model_name='software',
            name='mdm_download_link',
        ),
        migrations.RemoveField(
            model_name='software',
            name='mdm_file',
        ),
        migrations.RemoveField(
            model_name='software',
            name='tool_download_link',
        ),
        migrations.AddField(
            model_name='software',
            name='duration_options',
            field=models.JSONField(default=list, help_text="Example: ['1 Month','3 Months','6 Months']"),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('mdm_files', 'MDM Files'), ('tools', 'Tools')], max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
                ('price_paid', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('license_key', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SoftwareManagements.software')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
