# Generated by Django 6.0.2 on 2026-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0005_remove_software_license_keys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='software',
            name='duration_options',
        ),
        migrations.AddField(
            model_name='order',
            name='client_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='software',
            name='client_fields',
            field=models.JSONField(blank=True, default=list, help_text="Fields required from client e.g ['IMEI','Serial Number']"),
        ),
        migrations.AddField(
            model_name='software',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='service',
            field=models.CharField(blank=True, choices=[('imei', 'IMEI Service'), ('server', 'Server Service'), ('remote', 'Remote Service')], max_length=50, null=True),
        ),
    ]
