# Generated by Django 6.0.2 on 2026-03-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0006_remove_order_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='client_fields',
            field=models.JSONField(blank=True, default=list, help_text='Example: [{"name": "IMEI", "type": "text"}, {"name": "Screenshot", "type": "image"}]'),
        ),
        migrations.CreateModel(
            name='OrderClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='orders/client_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='SoftwareManagements.order')),
            ],
        ),
    ]
