# Generated by Django 6.0.2 on 2026-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0007_alter_software_client_fields_orderclientfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(choices=[('mdm_files', 'MDM Files'), ('tools', 'Tools'), ('services', 'Services')], max_length=20),
        ),
    ]
