# Generated by Django 6.0.2 on 2026-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoftwareManagements', '0008_alter_software_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='mdm_category',
            field=models.CharField(blank=True, choices=[('transsion', 'Transsion Devices'), ('samsung', 'Samsung Mobile'), ('hmd', 'HMD'), ('onfone', 'Onfone Mobile')], max_length=50, null=True),
        ),
    ]
