# Generated by Django 6.0.2 on 2026-03-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
