# Generated by Django 6.0.2 on 2026-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('manual_lumicash', 'Manual Payment'), ('manual_mpesa', 'Manual MPesa Payment'), ('manual_safaricom', 'Manual SafariCom Payment'), ('crypto', 'Crypto Payment'), ('deduction', 'Tool Download Deduction')], max_length=30),
        ),
    ]
