# Generated by Django 6.0.2 on 2026-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_herocarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('manual_lumicash', 'Manual Payment'), ('manual_mpesa', 'Manual MPesa Payment'), ('manual_safaricom', 'Manual SafariCom Payment'), ('manual_Bancobu', 'Manual Bancobu Enoti'), ('crypto', 'Crypto Payment'), ('deduction', 'Tool Download Deduction')], max_length=30),
        ),
    ]
